// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

struct Id{
    uint x;
    uint y;
};

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWStructuredBuffer<Id> ids;
int width;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    int pos = id.x + id.y * width;
    ids[pos].x = id.x;
    ids[pos].y = id.y;
}
